### PR TITLE
Intro screen

### PR DESCRIPTION
**Pull request by kingfisher13**

### CODE REVIEW

**Comment by kingfisher13** [comment]
Did you want me to include actual content? If so, has the client sent it yet?

**Comment by davidheyman** [comment]
Yes please. Content available here -> https://basecamp.com/1741364/projects/7935965/todos/161347885

**Comment by kingfisher13** [comment]
Content added.

**Comment by davidheyman** [comment]
Looks good! 2 things:
1. Can you make the video go full width?
2. The positioning of the modal causes it to spawn a scrollbar on my screen. Maybe just stick with the default positioning, even though it looks weird covering the header?

**Comment by kingfisher13** [comment]
-Should be full width now.
-Fixing the modal positioning affects all the modals. Is that fine?

**Pull request merged**
